name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: make build
