name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.5
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2024.1"
          install-go: false
      - name: Test
        run: make test
